### ISSUE TITLE
Avoid leaking the solution when provided with a word that is not part of the dictionary

### ISSUE THREAD

**Issue by David-5-1** [n1k0/wordlem#3]
Despite my lack of knowledge of elm, I suggest changing

https://github.com/n1k0/wordlem/blob/9bba38b172df70c9b9c53a9f6d00a5a8dfbc9db1/src/Main.elm#L225
with
```diff
-        I18n.AbsentFromDictionary { word = word } |> translate lang |> Err
+        I18n.AbsentFromDictionary { word = input } |> translate lang |> Err
```

**Comment by n1k0** [comment]
Muhahahaha good catch 😭 🤣

**Comment by n1k0** [comment]
Fixed by https://github.com/n1k0/wordlem/commit/f7191174c73de154f010f9732f9fcde0c7db8557
